# .streamlit/secrets.toml

[openai]
api_key = "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"